# Copyright (c) Microsoft Corporation
# All rights reserved.
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
# to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
# BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.



cluster:
  #common:
  cluster-id: sitonholy
  #
  #  # HDFS, zookeeper data path on your cluster machine.
  #  data-path: "/datastorage"

  # the docker registry to store docker images that contain system services like frameworklauncher, hadoop, etc.
  docker-registry:

    # The namespace in your registry. If the registry is docker.io, the namespace will be your user account.
    namespace: qzwlinux       #docker镜像下载位置

    # E.g., gcr.io.
    # if the registry is hub.docker, please fill this value with docker.io
    domain: 192.168.1.10:8888
    # If the docker registry doesn't require authentication, please comment username and password
    #username: <username>
    #password: <password>

    tag: v0.12.0              #版本名称

    # The name of the secret in kubernetes will be created in your cluster
    # Must be lower case, e.g., regsecret.
    secret-name: pai-secret


#Uncomment following lines if you want to customize yarn
#hadoop-resource-manager:
#  # job log retain time
#  yarn_log_retain_seconds: 2592000
#  # port for yarn exporter
#  yarn_exporter_port: 9459


#Uncomment following lines if you want to customize hdfs
#hadoop-data-node:
#  # storage path for hdfs, support comma-delimited list of directories, eg. /path/to/folder1,/path/to/folder2 ...
#  # if left empty, will use cluster.common.data-path/hdfs/data
#  storage_path:


# uncomment following if you want to change customeize yarn-frameworklauncher
#yarn-frameworklauncher:
#  frameworklauncher-port: 9086


rest-server:
  # database admin username
  default-pai-admin-username: admin
  # database admin password
  default-pai-admin-password: sitonholy 

#nfs配置
  nfs-host: 192.168.1.10
  nfs-user: root
  nfs-password: sitonholy
  nfs-dir: /ssd_data/pai/users                #nfs用户目录
  nfs-dir-file: /ssd_data/pai/users_dir_file  #nfs限制目录
  nfs-mount-point: /nfsmount/users            #挂载点路径

# uncomment following section if you want to customize the port of web portal
webportal:
  harbor-uri: http://192.168.199.100:8888     #harbor路径
#   server-port: 9286

# uncomment following if you want to change customeize grafana
# grafana:
#   port: 3000

# uncomment following if you want to change customeize drivers
drivers:
#  set-nvidia-runtime: false
#  # You can set drivers version here. If this value is miss, default value will be 384.111
#  # Current supported version list
#  # 384.111
#  # 390.25
#  # 410.73
  version: "410.73"                       #显卡驱动版本

# uncomment following if you want node-exporter listen to different port
# node-exporter:
#   port: 9100

# uncomment following if you want to customeize job-exporter
# job-exporter:
#   port: 9102
#   logging-level: INFO
#   interface: eth0,eno2

# if you want to enable alert manager to send alert email, uncomment following lines and fill
# the right values.
# alert-manager:
#   receiver: your_addr@example.com
#   smtp_url: smtp.office365.com:587
#   smtp_from: alert_sender@example.com
#   smtp_auth_username: alert_sender@example.com
#   smtp_auth_password: password_for_alert_sender
#   port: 9093 # this is optional, you should not write this if you do not want to change the port alert-manager is listening on

# uncomment following if you want to change customeize prometheus
# prometheus:
#   port: 9091
#   # How frequently to scrape targets
#   scrape_interval: 30
#
#   # if you want to use key file to login nodes
#   

# uncomment following section if you want to customize the port of pylon
# pylon:
#  port: 80

# uncomment following section if you want to customize the threshold of cleaner
# cleaner:
#  threshold: 94
#  interval: 60
